"""Regenerate the release grids from data/releases.json.

Run after editing the JSON:    python3 tools/build.py

Only the block between the RELEASES:START / RELEASES:END markers in each page
is rewritten. Everything else — hero, intro copy, nav, footer — is hand-written
and left untouched.
"""
import json, re, sys
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
START = "  <!-- RELEASES:START — generated by tools/build.py, do not edit by hand -->"
END = "  <!-- RELEASES:END -->"
BANNER_START = "  <!-- UPDATE-BANNER:START — generated by tools/build.py, do not edit by hand -->"
BANNER_END = "  <!-- UPDATE-BANNER:END -->"
STATS_START = "<!-- SITE-STATS:START — generated by tools/build.py, do not edit by hand -->"
STATS_END = "<!-- SITE-STATS:END -->"

# The actual decades — not new-jack-swing-productions or sampled, which
# aren't decade pages — each get their own scoped stats block too.
DECADE_PAGES = {"1980s", "1990s", "2000s", "2010s", "2020s"}

FLIP_SVG = ('<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" '
            'stroke-width="2.4" stroke-linecap="round"><path d="M3 12a9 9 0 0 1 15-6.7L21 8M21 '
            '12a9 9 0 0 1-15 6.7L3 16"/><path d="M21 3v5h-5M3 21v-5h5"/></svg>')

PLAY_SVG = '<svg viewBox="0 0 24 24" fill="currentColor"><path d="M8 5v14l11-7z"/></svg>'

FOLD_SVG = ('<svg class="fold-icon" width="24" height="24" viewBox="0 0 24 24" fill="none" '
            'stroke="currentColor" stroke-width="2.4" stroke-linecap="round" '
            'stroke-linejoin="round" aria-hidden="true"><path d="M6 9l6 6 6-6"/></svg>')

# An album tracklist is numbered — "01. Her", "05 — Sleaze", "3. Can We Try Again".
# A single lists versions of one song, never numbered. That is the only tell the
# source site gives us, so it is what decides LP vs Single. A bare digit followed
# by a space is not enough ("8 Days A Week (Sax Mix)" is a single), so a lone
# number needs its separator, or a two-digit index its leading zero.
# Mirrored in releaseFormat() in script.js, for the card the 404 page builds.
NUMBERED = re.compile(r'^\s*(?:\d{1,2}\s*[–—.)]|\d{2}\s)')

# A single's "01 - ", "04. " etc. is just pressing order, not a meaningful
# sequence — once something has classified as a Single, that prefix is only
# noise on the back of the card, so it's stripped for display and the list
# is alphabetized instead of kept in pressing order. Broader than NUMBERED
# (also catches the plain hyphen a single uses specifically to dodge that
# regex, e.g. "01 - Fool Around"). Mirrored in stripTrackNumber() in script.js.
TRACK_NUM_PREFIX = re.compile(r'^\s*\d{1,2}\s*[-–—.)]\s*')


def esc(s):
    """& first, then the inch mark. Matches the entities already in the pages."""
    return s.replace("&", "&amp;").replace("″", "&Prime;")


def fmt(r):
    """LP or Single. "format" in the JSON wins where the tracklist can't tell."""
    if r.get("format"):
        return r["format"]
    return "LP" if any(NUMBERED.match(t) for t in r["tracks"]) else "Single"


def video_btn_html(r):
    """A release can carry one or more YouTube clips. data-videos is a JSON
    array of {id, label} read by the delegated handler in script.js — one
    button either plays straight or, with more than one clip, opens a small
    chooser. HTML-attribute-escaped (not esc(), which is for text nodes)
    since label text can carry an apostrophe into a single-quoted attribute."""
    videos = r.get("videos")
    if not videos:
        return ""
    attr = json.dumps(videos, ensure_ascii=False).replace("&", "&amp;").replace("'", "&#39;")
    return (f'\n          <button type="button" class="video-btn" data-videos=\'{attr}\' aria-label="Watch video">\n'
            f'            {PLAY_SVG}\n'
            f'          </button>')


def display_tracks(r):
    """(display_text, original_text) pairs — original is what "missing"
    matches against; display is what's shown. A Single's tracks are
    stripped of their pressing-order number and alphabetized; an LP or
    EP keeps its real sequence untouched."""
    tracks = r["tracks"]
    if fmt(r) != "Single":
        return [(t, t) for t in tracks]
    pairs = [(TRACK_NUM_PREFIX.sub("", t), t) for t in tracks]
    pairs.sort(key=lambda p: p[0].lower())
    return pairs


def card_html(r):
    artist, title = esc(r["artist"]), esc(r["title"])
    missing = set(r.get("missing", []))
    lis = "\n".join(
        f'            <li class="missing" itemprop="track" itemscope itemtype="https://schema.org/MusicRecording"><span itemprop="name">{esc(display)}</span></li>' if orig in missing
        else f'            <li itemprop="track" itemscope itemtype="https://schema.org/MusicRecording"><span itemprop="name">{esc(display)}</span></li>'
        for display, orig in display_tracks(r)
    )
    legend = ('\n            <span class="legend"><span></span>missing from collection</span>'
              if missing else "")
    note = (f'\n          <p class="note">{esc(r["note"])}</p>' if r.get("note") else "")
    video_btn = video_btn_html(r)
    # schema.org/MusicAlbum on the whole card: this is what lets a search
    # engine understand "artist X released album Y on label Z in year W with
    # these tracks" directly from markup already on the page, rather than a
    # separate JSON-LD blob to keep in sync — byArtist/recordLabel nest their
    # own itemscope (a MusicGroup / Organization each need their own "name"),
    # and datePublished is a hidden <meta> since the year isn't printed on the
    # card itself (it's the enclosing year-group heading's job).
    return f'''    <div class="card">
      <div class="card-inner" role="button" tabindex="0" aria-pressed="false" style="--cover-img:url('imgs/{r["image"]}')" itemscope itemtype="https://schema.org/MusicAlbum">
        <meta itemprop="datePublished" content="{esc(r["year"])}">
        <div class="face front">
          <img src="imgs/{r["image"]}" alt="{artist} – {title} sleeve" loading="lazy" itemprop="image">
          <span class="format">{fmt(r)}</span>
          <span class="flip-hint" aria-hidden="true">
            {FLIP_SVG}
          </span>
        </div>
        <div class="face back">
          <div class="back-head">
            <div class="back-head-text">
              <p class="artist"><span itemprop="byArtist" itemscope itemtype="https://schema.org/MusicGroup"><span itemprop="name">{artist}</span></span> — <span itemprop="name">{title}</span></p>
              <p class="label-name"><span itemprop="recordLabel" itemscope itemtype="https://schema.org/Organization"><span itemprop="name">{esc(r["label"])}</span></span></p>
            </div>{video_btn}
          </div>
          <ul class="tracks">
{lis}
          </ul>{note}
          <div class="back-foot">{legend}
            <button type="button">Flip back</button>
          </div>
        </div>
      </div>
    </div>
'''


def grids_html(releases):
    """Year headings, each a <details> that folds its grid open — years keep
    first-seen order. The anchor id lives on .grid, not the summary: a
    browser only auto-opens a closed <details> when the fragment target is
    one of its hidden descendants, not the summary or the details itself.

    All of it sits inside one .timeline wrapper so the connecting rail
    (style.css) can be a single element spanning edge to edge, rather than
    per-year segments that would need to line up across the gap between
    them — its height is just the wrapper's content height, so it grows
    and shrinks automatically as years open and close.

    The first year-group starts open — otherwise a page's first visit
    shows nothing but collapsed headings above the fold. Every later
    year still opens closed, same as before."""
    years = list(dict.fromkeys(r["year"] for r in releases))
    out = ['  <div class="timeline">\n']
    for i, y in enumerate(years):
        cards = "\n".join(card_html(r) for r in releases if r["year"] == y)
        open_attr = " open" if i == 0 else ""
        out.append(f'  <details class="year-group"{open_attr}>\n'
                   f'    <summary class="year-rule">{y}{FOLD_SVG}</summary>\n'
                   f'    <div class="grid" id="y{y}">\n\n{cards}\n    </div>\n'
                   f'  </details>\n')
    out.append('  </div>\n')
    return "\n".join(out)


def jump_html(all_releases):
    """The nav entry a correctly hand-maintained page should have for each
    year that's ever carried a release, in first-seen order: a link for a
    year with something visible, a "coming soon" span — same wording CLAUDE.md
    prescribes, same pattern as the nav dropdown's unpublished decades — for
    a year emptied entirely by hiding. Takes the *unfiltered* release list so
    it knows about emptied years; only used to check the hand-written nav for
    drift, never spliced in (see CLAUDE.md's "A new year")."""
    years = list(dict.fromkeys(r["year"] for r in all_releases))
    if len(years) < 2:
        return None  # a one-button jump row is pointless
    visible_years = {r["year"] for r in all_releases if not r.get("hidden")}
    entries = "".join(
        f'      <a href="#y{y}">{y}</a>\n' if y in visible_years
        else f'      <span title="coming soon">{y}</span>\n'
        for y in years
    )
    return ('    <nav class="year-jump" aria-label="Jump to year">\n'
            '      <span class="year-jump-label">Jump to</span>\n'
            f'{entries}    </nav>')


def banner_bullet(p, prefix=None):
    """Most entries are a release count against a page; a few are a plain
    feature announcement (a new page, a redesign) that doesn't have a count
    to report. "label" opts an entry into the second form: the whole bullet
    becomes that text, linked. prefix folds an older update's date onto its
    first bullet, so banner_html can flatten every recent update into one
    line without a separate heading per date."""
    lead = f'<span class="prev-date">{esc(prefix)}</span> ' if prefix else ''
    if "label" in p:
        return f'      <li>{lead}<a href="{esc(p["href"])}">{esc(p["label"])}</a></li>'
    plural = "" if p["count"] == 1 else "s"
    return (f'      <li>{lead}{p["count"]} release{plural} added to '
            f'<a href="{esc(p["href"])}">{esc(p["name"])}</a></li>')


def banner_html(recent):
    """The homepage's dismissible "recently added" strip, a lower third along
    the bottom of the hero video, sourced from the tail of data/updates.json
    (newest first — see the call site for how many). One flat bulleted
    line: the newest entry's own items, then any older ones' items with
    the date folded onto the first bullet of that date's group — stacking
    a full heading-plus-list per date instead made the overlay taller than
    the video itself.
    Dismissal in script.js is keyed to data-update (the *newest* entry's
    date), so a later entry reappears even if an older one was dismissed.
    Empty when there's no update yet, leaving the markers in index.html
    with nothing between them."""
    if not recent:
        return ""
    newest, older = recent[0], recent[1:]
    date = datetime.strptime(newest["date"], "%Y-%m-%d").strftime("%b %-d")
    items = [banner_bullet(p) for p in newest.get("pages", [])]
    for u in older:
        pdate = datetime.strptime(u["date"], "%Y-%m-%d").strftime("%b %-d")
        for i, p in enumerate(u.get("pages", [])):
            items.append(banner_bullet(p, prefix=pdate if i == 0 else None))
    items_html = "\n".join(items)
    return (f'  <div class="update-banner" data-update="{esc(newest["date"])}">\n'
            f'    <button class="dismiss" type="button" aria-label="Dismiss">&times;</button>\n'
            f'    <p class="date"><span class="tag">New</span> {date}</p>\n'
            f'    <ul class="breakdown">\n{items_html}\n    </ul>\n'
            f'  </div>\n')


def stats_html(n_releases, n_tracks, n_artists, note=None):
    """Three big numbers — every visible release, every track (each
    version counts on its own, same as the per-page counts main()
    prints), and every distinct "artist" string (exact match, so a
    featuring credit like "Ray J feat. Brandy" counts separately from
    plain "Ray J" — a real discography credit, not a rigorous unique-
    person count). Used both for the homepage's site-wide total and,
    with `note` set, for a single decade page's own count (initSiteStats
    in script.js animates whichever numbers it finds, no page-specific
    wiring needed either way)."""
    note_html = f'\n  <p class="stats-note">{esc(note)}</p>' if note else ''
    return ('  <div class="site-stats">\n'
            f'    <div class="stat"><span class="stat-num">{n_artists:,}</span>'
            f'<span class="stat-label">artists</span></div>\n'
            f'    <div class="stat"><span class="stat-num">{n_releases:,}</span>'
            f'<span class="stat-label">releases</span></div>\n'
            f'    <div class="stat"><span class="stat-num">{n_tracks:,}</span>'
            f'<span class="stat-label">songs</span></div>\n'
            f'  </div>{note_html}\n')


def splice(path, start, end, body):
    src = path.read_text(encoding="utf-8")
    if start not in src or end not in src:
        sys.exit(f"error: {path.name} is missing its splice markers")
    head, rest = src.split(start, 1)
    _, tail = rest.split(end, 1)
    new = f"{head}{start}\n{body}{end}{tail}"
    changed = new != src
    path.write_text(new, encoding="utf-8")
    return changed


def main():
    data = json.loads((ROOT / "data" / "releases.json").read_text(encoding="utf-8"))
    total_releases = 0
    total_tracks = 0
    total_artists = set()
    for page, all_releases in data.items():
        path = ROOT / f"{page}.html"
        n_hidden = sum(1 for r in all_releases if r.get("hidden"))
        releases = [r for r in all_releases if not r.get("hidden")]
        changed = splice(path, START, END, grids_html(releases))
        n_missing = sum(len(r.get("missing", [])) for r in releases)
        n_lp = sum(1 for r in releases if fmt(r) == "LP")
        n_ep = sum(1 for r in releases if fmt(r) == "EP")
        n_book = sum(1 for r in releases if fmt(r) == "Book")
        n_single = len(releases) - n_lp - n_ep - n_book
        other = (f", {n_ep} EP" if n_ep else "") + (f", {n_book} Book" if n_book else "")
        hidden = f", {n_hidden} hidden" if n_hidden else ""
        page_tracks = sum(len(r["tracks"]) for r in releases)
        page_artists = {r["artist"] for r in releases}
        total_releases += len(releases)
        total_tracks += page_tracks
        total_artists |= page_artists
        print(f"  {page}.html: {len(releases)} releases "
              f"({n_lp} LP, {n_single} single{other}), "
              f"{page_tracks} tracks, {n_missing} flagged{hidden}"
              f"{'  (updated)' if changed else '  (no change)'}")
        if page in DECADE_PAGES:
            page_stats_changed = splice(
                path, STATS_START, STATS_END,
                stats_html(len(releases), page_tracks, len(page_artists),
                           note=f"* just the {page[:4]}'s")
            )
            if page_stats_changed:
                print(f"    stats block updated ({len(releases)} releases, {page_tracks} songs, "
                      f"{len(page_artists)} artists)")
        jump = jump_html(all_releases)
        if jump and jump not in path.read_text(encoding="utf-8"):
            print(f"    note: the year-jump nav in {page}.html is out of date — "
                  f"years changed. Update it by hand or ask Claude.")

    stats_changed = splice(ROOT / "index.html", STATS_START, STATS_END,
                            stats_html(total_releases, total_tracks, len(total_artists)))
    print(f"  index.html: site stats ({total_releases} releases, {total_tracks} songs, "
          f"{len(total_artists)} artists)"
          f"{'  (updated)' if stats_changed else '  (no change)'}")

    updates_path = ROOT / "data" / "updates.json"
    updates = json.loads(updates_path.read_text(encoding="utf-8")) if updates_path.exists() else []
    recent = list(reversed(updates[-2:]))  # newest first; just one previous update, not the full history
    changed = splice(ROOT / "index.html", BANNER_START, BANNER_END, banner_html(recent))
    status = f"{recent[0]['date']}, {recent[0]['count']} releases" if recent else "none"
    print(f"  index.html: update banner ({status})"
          f"{'  (updated)' if changed else '  (no change)'}")


if __name__ == "__main__":
    main()
